version: "3.8"
services:
  server:
    build:
      context: server
    ports:
      - 9010:9001
    environment:
      - JVM_XX_OPTS=-Ddisable.watchdog=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9001
  proxy:
    build:
      context: proxy
    ports:
      - 25565:25565
      - 9011:9001
    environment:
      - JVM_XX_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9001
    depends_on:
      - server
